apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  user: dXNlcg==            # base64('user')
  password: cGFzc3dvcmQ=    # base64('password')
  rootpassword: cm9vdHBhc3N3b3Jk  # base64('rootpassword')
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  jwt: Y2hhbmdlLW1l          # base64('change-me')
